### ISSUE TITLE
Debug puts in the controller and model

### ISSUE THREAD

**Issue by nbulaj** [apotonick/gemgem-hanami#1]
Hi. Take a look to the [`sheets_controller.rb`](https://github.com/apotonick/gemgem-hanami/blob/master/apps/web/controllers/sheets_controller.rb#L58)and [`operation/create.rb`](https://github.com/apotonick/gemgem-hanami/blob/29bfb6ee8802b228994dabd20cbbf25f65ba435b/apps/web/sheet/operation/create.rb) - you forget to remove `puts` :)

**Comment by apotonick** [comment]
Hahaha, thanks, but that's OK. This repo is pure playground ATM. :laughing: :rocket:
